### ISSUE TITLE
Hullogram working straight from the browser

### ISSUE THREAD

**Issue by HiggsOfChaos** [hull-graveyard/hullagram#20]
Hi,

I use a windows machine so I am not familiar with the cli configuration steps involved in building the app.

Can't hullogram just work from a browser like  conventional HTML5 files?

Seun

**Comment by sbellity** [comment]
This app has been developed Grunt based tools...
You could just serve the /app directory which contains all the components but : 
- there are a few dependencies that are missing from the repo and have to be installed with bower (ratchet and font-awesome)
- If you want to modify the app you need the build tools to rebuild it 

Or... A quick way to get setup to run without the tools could be... to :

#### manually add the missing dependencies

The required files are 

```
/components/ratchet/dist/ratchet.css
/components/font-awesome/css/font-awesome.css
```

#### change Hull.init to load the components from the widgets directory instead of the pre-built versions :

Remove  :

```
  <!-- build:js application.js -->
  <script src="scripts/templates.js"></script>
  <script src="scripts/widgets.js"></script>
  <!-- endbuild -->
```

And replace : 

```
<script type='text/javascript'>
Hull.init({
  appId: '5103a56f93e74e3a1f000012',
  orgUrl: 'http://hull-demos.hullapp.io',
  debug: true
});
</script>
```

with : 

```
<script type='text/javascript'>
Hull.init({
  appId: '5103a56f93e74e3a1f000012',
  orgUrl: 'http://hull-demos.hullapp.io',
  sources: { default: '/widgets' }
});
</script>
```

**Comment by HiggsOfChaos** [comment]
Hi,

I downloaded the dependencies and added them. I replaced the sources directive in the init but it doesn't seem to be working.

Is there a tutorial that shows how the app was built step-by-step?
